### ISSUE TITLE
Trying to join ferment pub doesn't work

### ISSUE THREAD

**Issue by arj03** [fermentation/ferment#7] opened 2016-10-05 13:27 UTC
Getting this error:

Uncaught Exception:
UsageError: Param 0 is required
    at Error.ZE (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/zerr/index.js:11:42)
    at Object.ZError [as MissingParam](/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/zerr/index.js:13:14)
    at validate (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/muxrpc-validation/index.js:122:48)
    at Object.<anonymous> (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/muxrpc-validation/index.js:58:17)
    at Object.<anonymous> (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/hoox/index.js:3:17)
    at Object.hooked [as add](/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/hoox/index.js:10:15)
    at /home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/lib/invite-with-scope.js:222:50
    at Object._requests.(anonymous function) (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/packet-stream/index.js:37:5)
    at PacketStream.destroy (/home/arj/.nvm/versions/node/v6.1.0/lib/node_modules/ferment/node_modules/packet-stream/index.js:73:66)

**Comment by mmckegg** [comment] 2016-10-05 13:51
Strange, just tried that out myself and can't seem to reproduce.

@arj03 Where did the error appear? Was it in a popup, the developer console or the terminal?

**Comment by arj03** [comment] 2016-10-05 14:22
I got it in a popup. But after restarting, it seems to be working.

**Comment by dominictarr** [comment] 2016-10-06 08:21
I am also having a problem. I see this:

![ferment_join-pub](https://cloud.githubusercontent.com/assets/259374/19144988/408786fc-8c09-11e6-9566-4b9ef7030968.png)

I would like to see what sort of error it is (since I can help fix it ;)
also, I notice that you are opening another electron window to do the join code?
That means the popup has it's own dev tools and makes it hard to see the error!

I managed to extract:

```
Error: could not connect to server
    at /home/dominic/c/ferment/lib/invite-with-scope.js:194:30
    at /home/dominic/c/ferment/node_modules/ssb-client/index.js:87:20
  Error: could not connect to sbot
    at /home/dominic/c/ferment/node_modules/ssb-client/index.js:87:23
    at next (/home/dominic/c/ferment/node_modules/multiserver/compose.js:21:20)
    at /home/dominic/c/ferment/node_modules/multiserver/compose.js:25:9
    at /home/dominic/c/ferment/node_modules/multiserver/node_modules/secret-handshake/secure.js:11:20
    at /home/dominic/c/ferment/node_modules/pull-handshake/index.js:10:5
    at /home/dominic/c/ferment/node_modules/pull-handshake/index.js:23:13
    at callback (/home/dominic/c/ferment/node_modules/pull-pushable/index.js:69:7)
    at drain (/home/dominic/c/ferment/node_modules/pull-pushable/index.js:56:39)
    at Function.read.end (/home/dominic/c/ferment/node_modules/pull-pushable/index.js:31:5)
  Error: challenge not accepted
    at abort (/home/dominic/c/ferment/node_modules/multiserver/node_modules/secret-handshake/handshake.js:29:43)
    at Object.cb (/home/dominic/c/ferment/node_modules/multiserver/node_modules/secret-handshake/handshake.js:35:22)
    at drain (/home/dominic/c/ferment/node_modules/pull-reader/index.js:42:23)
    at /home/dominic/c/ferment/node_modules/pull-reader/index.js:59:18
    at /home/dominic/c/ferment/node_modules/pull-reader/index.js:20:7
    at drain (/home/dominic/c/ferment/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/dominic/c/ferment/node_modules/stream-to-pull-stream/index.js:162:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:493:12)
```

half way down we see the reason "challenge not accepted" that means the tcp connection worked, but then something broke.

**Comment by dominictarr** [comment] 2016-10-06 08:21
also note the OS borders around the inner dialog box

**Comment by mmckegg** [comment] 2016-10-06 08:39
That seems to be what happens when the server locks up.

If I restart it, it will probably start working. 

Some of those display glitches are fixed in the latest release. Still need to centre the dialog though.

**Comment by dominictarr** [comment] 2016-10-06 11:18
I'm gonna work on a monitoring thing to give us performance stats. in the mean time, although I hate this, maybe make a thing to just crash and restart the server every so often. how long does it take to lock?

**Comment by mmckegg** [comment] 2016-10-06 11:46
It's unpredictable. I've had it lock up almost immediately after restarting.

I think you're right though that it's just busy doing something else. It does seem to come back again. Starting to almost wonder if it is accepting invites that breaks it.

But yeah, an auto restart is probably better than what's happening right now. Don't think anyone has managed to join since about 6 hrs ago.

**Comment by mmckegg** [comment] 2016-10-06 11:46
@dominictarr have you managed to join yet?

**Comment by mmckegg** [comment] 2016-10-06 13:19
I've turned off torrent mirroring on my server for now. This seems to have improved the situation. There's some sort of issue with webtorrent where cpu usage is way higher than it should be when sharing lots of these small ogg files. This might be what is prompting ssb to fail.

Only downside is that I'll have to leave my computer on all night to seed the files. 

/cc @feross

**Comment by dominictarr** [comment] 2016-10-06 19:58
how small are the files? under 5 mb?

**Comment by mmckegg** [comment] 2016-10-06 21:04
No, most are bigger than that. I'm using a high quality vbr ogg vorbis codec right now. Ends up being around 2 MB a minute. There are files as large as 120 MB in there at the moment. But most of  the are around 7 - 16 MB

**Comment by mmckegg** [comment] 2016-10-06 21:06
Just checked the server this morning and it had locked up again. Looks like the torrent thing was just making my machine slow, but not actually the primary cause.

**Comment by feross** [comment] 2016-10-07 06:51
WebTorrent shouldn't do this. Plan to fix this soon.

**Comment by 01Leviathan10** [comment] 2017-06-15 05:44
<img width="1280" alt="screen shot 2017-06-15 at 07 42 59" src="https://user-images.githubusercontent.com/14329139/27166951-61e145f8-519e-11e7-8d91-78dee7c21b8d.png">

**Comment by ahdinosaur** [comment] 2017-06-15 09:37
hey @01Leviathan10, there's a note about this on the [README](https://github.com/mmckegg/ferment/blob/master/README.md)

> Ferment Pub offline
>
> So this means you can't join right now. I'm in the process of rewriting ferment so that it can work with any standard ssb pub. Once this is done, you'll be able to use the app again, and I won't have to worry about bandwidth issues!
>
> More info: https://github.com/mmckegg/ferment/issues/48

**Comment by Marak** [comment] 2017-07-31 02:37
Closing this issue since the central pub is still offline and won't be back online until we've released our next Beta version ( which will be announced soon ).

We've recently added more developers and resources to help get this project off the ground again.

Sorry for the inconvenience. Please check back soon for updates.

**Closed by Marak** 2017-07-31 02:37 UTC
